name: keyboard_utils
description: fork from https://github.com/hello-coder-xu/keyboard_utils.git
version: 1.0.2
homepage: https://github.com/kapibara91/keyboard_utils

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: br.com.keyboard_utils
        pluginClass: KeyboardUtilsPlugin
      ios:
        pluginClass: SwiftKeyboardUtilsPlugin
